spring.application.name=Laboratorio de Pruebas de Software

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:mem:a61cff38-3261-41b6-a8a8-2e9540bc36d2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
